### PR TITLE
Update login.ztml

### PR DESCRIPTION
**Pull request by japp-0xlabs**
XSS fixes.

If form action is empty, the target is self script. PHP_SELF not needed.

### CODE REVIEW

**Comment by allebb** [comment]
This was previously added to ensure legacy browser support but I guess as the latest theme is using a whole load of jQuery and HTML5 I guess we could remove the attribute value for no other reason but to remove a few characters from the login template.

**Comment by japp-0xlabs** [comment]
I think other little reason could be XSS patch as I said, if you don't sanitize PHP_SELF and you try something like /index.php/%22%3E%3Cscript%3Ealert%28document.cookie%29%3C%2fscript%3E you will get nice javascript alert.

**Comment by 5050** [comment]
(only for note) Since HTML5,  action=""  is reported as an error by html validator (http://validator.w3.org/). when empty, the directive "action" should be completely removed.

**Comment by allebb** [comment]
Cheers 5050, I'll remove the attribute altogether :+1:

**Comment by allebb** [comment]
Fixed: https://github.com/zpanel/zpanelx/commit/a8a540ddca82209f9510517b8b1c368da8ef35fb - Good call there 5050!

**Pull request merged**
