### PR TITLE
Added AJAX compatibility and security to binaries

### PR DESCRIPTION
**Pull request by VJftw**
## READ FIRST

Execute this SQL to update the module folder name in the database!

``` sql
UPDATE `zpanel_core`.`x_modules` SET `mo_folder_vc` = 'zpanel_config'
WHERE `x_modules`.`mo_folder_vc` = 'zpanelconfig';
```

Further notes:
- zpanel_config module updated to use the implemented secure way of
  running the daemon.
- files in the bin folder cannot be accessed via apache (thus these
  can't be executed anymore via control.example.com/bin/daemon.php)
- Tested on Ubuntu and should work on CentOS. Windows needs testing, the
  only thing that could go wrong with Windows is that the daemon file may
  not be called in Windows if the default directory in php is not the
  panel one.

### CODE REVIEW

**Comment by andykimpe** [comment]
it looks pretty good

pity I can accept the box Merge Pull Request is grayed

We can’t automatically merge this pull request.

Use the command line to resolve conflicts before continuing.

bobby please use command for accept pull request

**Comment by allebb** [comment]
Before I merge this needs full testing on CentOS, Ubuntu and Windows as per our internal development rules (we no longer accept things that haven't been tested on all platforms as generally stuff breaks and causes all kinds of crap lol). - We'll need to direct the support team here to test this change!

**Comment by allebb** [comment]
This is now redundant, my changes last night has now removed the ability to 'force run' the daemon directly from the browser (control panel), instead you would need to 'queue a full run' and then wait for the next five minute interval for it to run, so now execution of the daemon is now solely done using the CRON job, I've decided to do this for security reasons, if people hate the fact that this feature is now removed then I'd recommend a third-party module be developed.

**Comment by VJftw** [comment]
What about AJAX capability?

**Comment by allebb** [comment]
I'm not sure I follow?

Are you saying why can't we use Ajax to make the request? - People (security hardcore) are really against direct manipulation of the back-end via webpages and for this reason I've decided to just disjoin any kind of issues that may arise in future, this will mean that we no longer have to run the daemon with permissions of the web server and can now be executed under a system account specified in the cron! - Seems safer in my opinion and less hassle in the long run. I don't see how Ajax could solve this problem?

.....or are you saying there is an issue at present with making Ajax requests? - If so this is the first of heard of it and in which case a bug report should be logged so we can track changes (changelog purposes) with the next release.

**Comment by VJftw** [comment]
That's not what I meant, however, that's a fair idea using CRON. I imagine this is implemented in Windows too using the Task Scheduler?
The way with AJAX, if you looked at the submitted code for the zpanel_config module, was that as only logged in Administrators can access the ZPanel Config module, only they would be able to execute the extra method inside the controller.ext.php that runs the daemon as the Apache process. 
If you're going to 'hardcore' on security, then it's probably not recommended to run the daemon often as Root? Anyone can write a module which can have a simple OnDaemonRun hook to extract information such as root passwords from files such as the cnf/db.php one, etc. and wreck havoc inside the server. I know we say that third party modules are installed at your own peril but i've written this already now, and personally I see no issues in not using it.

What I was asking about, was the AJAX compatibility of ZPanel.. Right now there's no support for it at all, and I noticed that there's an ajax folder in the dryden that was made 7 months ago, so you'll need to make similar changes. For example, if you create an asynchronous request to the server, even with the correct headers, ZPanel will still throw out everything with the user templates. My implementation checks for the Xmlhttprequest header before it includes the stylesheet which I thought it was quite clear in my changes to dryden/runtime/controller.class.php.

**Comment by allebb** [comment]
Well to be honest, I didn't read all the code I will admit that I just read the commit message (I wish I had time to read all the code for everything lol!)

Yeah, Windows servers are using a custom Task scheduler type system (Not Windows Task scheduler though) to implement CRON jobs running in the same way as they do on Linux.

I see what you are saying but  I'm not sure I agree with this statement:- 

'If you're going to 'hardcore' on security, then it's probably not recommended to run the daemon often as Root? Anyone can write a module which can have a simple OnDaemonRun hook to extract information such as root passwords from files such as the cnf/db.php one, etc. and wreck havoc inside the server. I know we say that third party modules are installed at your own peril but i've written this already now, and personally I see no issues in not using it.'

In this situation you would be basically logging into ZPanel as 'root' or 'administrator', if you install a module which can get passwords and other stuff then how does that differ from installing an application on a server using 'root' or 'administrator' that can do the same? - This will be solved when we start auditing modules that people will submit to the modules repo  site (of whcih will be the only place (by default) that people can install thirdparty modules from).

My point is that ZPanel already uses the CRON to execute these tasks so it would not be adding any extra features/risks. - We can't remove the CRON functionality as ZPanel relies so heavily on it! - If a linux whiz wanted to provide a solution for all the file permissions complexities then I'd be whiling to remove the CRON running as Root (it runs as root as it has to be able to action all kinds of various daemon generated data such as Webalizer data, Mail data, Nginx data, Files that have been uploaded using the FTP daemon etc).

ZPanelX never originally had Ajax support as I didn't see a need for it when I started work on this version 2+ years ago. I agree, that this would be a great benefit now but I've been concentrating on the next version of ZPanel which has support for all of these features and far superior security (using Linux system accounts instead meaning that files and web data is associated to a multiple system users which should then not add in so many complex virtual user to system user mappings). - The way I see it is that ZPX although used by many, the main developer of the project (myself) needs to start concentrating on the next version of ZPanel to ensure that we don't fall behing (support for PHP 5.5, greater security etc. etc.) that is why overhauling the existing ZPX would be a nightmare as opposed to starting from scratch building exactly what we need and without rushing it!

I'll read through the code now, I apologise I didn't before properly but I have to be careful how I balance my time and when I originally read your commit message I just assumed it was for implementing the the 'force daemon run' feature....

**Comment by VJftw** [comment]
Haha, that's fair enough :+1: 

Ok, that's good, and I agree with that, the main reason I came out with that is because i've seen a few posts on the forums saying that it's apparently bad in a way that ZPanel uses the Root account. A while back when I proposed a separate user group to help secure ZPanel from other users on the server as described in this post: http://forums.zpanelcp.com/Thread-permissions-httpd-vhosts-conf?pid=47714#pid47714
Following on from that, notice that Apache, MySQL and ProFTPD all run under their own processes and I imagine that they don't use the Root account to make any changes to configuration because it's  not necessary. They just own what they use and only use Root upon installing. I know we're getting into the Stormwind territory greatly here (looking forward to it :) ), and even off the topic from this commit. 

Well yeah it's up to you :) I can wait for Stormwind, I just saw in the Staff Room that people wanted a fix to the RunDaemon bug and I implemented this as well as I noticed the Ajax folder in the Dryden and assumed that Ajax was currently on the roadmap.

**Comment by jasondavis** [comment]
@VJftw As far as I remember, the `AJAX` folder is something I added in that is currently only used to saving the drag and drop positions of the module category boxes on the home screen.

@bobsta63 That sounds really interesting, the talk of adding separate Linux User accounts in the new version...if I read that correctly so that it is more in line with how CPanel and some of the other top panels work.  I think that will truly be amazing!  Would love to see or hear more about the newer project.  I think you had said you might build it on top of Laravel, which again will really be awesome.  If it is built on Laravel and does the separate User accounts on the OS....those 2 features I think will really seriously push ZPanel (or whatever you call this new one) into a new league and I think it will attract a ton of new faces that will be interested in the project.  It sounds badass =)

Just an idea...for the Plugin system, it would be really cool to do something more similar to WordPress and allow for a user to easily update plugins to newer versions.  As well as the main application...that would be amazing if it was possible to just hit a couple buttons and have the application update itself to a newer version the way WordPress does.  I know this might be the tricky part since ZPanel if often editing non-web accessible files and config stuff....so I realize this might not even always be possible.  I am sure you have thought of all these things, I guess I am mentioning them since you also mentioned taking your time and doing everything just right =)

The future is bright, keep up the work my friend

**Pull request closed without merging**
