### PR TITLE
Loader inc

### PR DESCRIPTION
**Pull request by trojanspike**
if you try it you'll see that the autoload func causes multiple issets etc - 

```
   if (isset($_GET['module'])) {
      echo "# ISSET - MODULE";
```

### CODE REVIEW

**Comment by trojanspike** [comment]
Am wonder were you/s talk or plan what the next steps are for zpanel.

**Comment by motters** [comment]
Hey Pal,

Did not see this issue submission myself and Bobby have been mega busy over the past month. 

I'll send Bobby an email tomorrow so he can review all your commits :)

For ZPanelX now it looks likes its just fixing bugs and making it as stable as possible, as we are developing a the next version of ZPanel (stormwind http://forums.zpanelcp.com/thread-7342.html).

We generally chat about development of the forums and emails with the odd skype call if necessary lol 

Cheers for the commits/help as well :D

**Comment by trojanspike** [comment]
@motters It's a bug that would usually go un-noticed because there's no error as such , just decreases the speed.
If u can imagine for every new class instance the isset & files static function are run - when they only really need to be run once.

Bobby is saying that it's just going to be a private repo , how would I be able to get involved in the development? If at all

**Comment by allebb** [comment]
As this is performance improvements (the autoloader) - I didn't notice that before!!  - Well spotted! - Also as the Vagrant file is useful for development I'll also merge this too, this doesn't introduce new features into the panel so I'm happy to merge as per Motters advice above.

The new version of ZPanel is being developed in a private repo, that is correct... To keep things untainted whilst I develop it I do not allow pull requests as things just get messy etc. - I'll release the code up to GitHub for beta testing once it is nearer completion at this point developers can open pull-requests etc. etc.

Cheers,
Bobby

**Comment by allebb** [comment]
Dang, closed by mistake.. re-opening and then merge!

**Pull request merged**
