### PR TITLE
Fixes and Updates

### PR DESCRIPTION
**Pull request by jacobgelling**
Updated PhpSysInfo, phpMyAdmin and Rouncube (fixes http://bugs.zpanelcp.com/view.php?id=698), removed some un-needed files and also fixed bug in http://bugs.zpanelcp.com/view.php?id=661. I've added the previous panel headings fix to the light theme variant.

(I think) I managed to fix my annoying auto merge problem as well :smile:

### CODE REVIEW

**Comment by lottfy** [comment]
As I see you round roundcube  to 0.9.5 where's sql. patches mate.

**Comment by jacobgelling** [comment]
I'll add them just now :wink: 

Why doesn't Windows have a Roundcube SQL script? :confused:

**Comment by jacobgelling** [comment]
All is now working and ready to merge :+1: 

Still not sure where the Windows Roundcube SQL script is though.

**Comment by allebb** [comment]
Cheers Jacob, pleased to see you put back in the session checking in PHPSysInfo :)

Although straight forward thanks for the various updates buddy, saved me a ton of time of which is good as I'm busy with a few other things at present :)

**Comment by jacobgelling** [comment]
Glad I could help :wink: If the auto merge isn't working I can easily fix it later btw.

**Comment by allebb** [comment]
No, it was fine buddy, I just had a quick look through the changes to make
sure I couldn't see any issues that you may not have thought about (given
that we make a few changes such as session checks and phpMyAdmin config
tweaks). - All merged now though :)

**Comment by lottfy** [comment]
@ bobsta63 we using  0.9.2 so there is .3 .4 .5 so must apply sql patches which come with version correct me

**Comment by jacobgelling** [comment]
@lottfy Ah, I understand what you mean by SQL patches now. I didn't think any changes were made to the database from 0.9.2 to 0.9.5. I'll investigate it and open another pull request if needed tomorrow.

**Comment by lottfy** [comment]
also go to \etc\build\config_packs and update roundcube with sql file"come with roundcube 0.9.5" so who will install zp at clean machine installer aooly this .sql not older

**Comment by jacobgelling** [comment]
@lottfy I don't think any patches need to be applied as nothing has changed database-wise since the other Roundcube version installed.

**Comment by lottfy** [comment]
After check nothing need to changes mate good work :+1:

**Pull request merged**
