### PR TITLE
Bug in Client Notice Manager with Greek characters

### PR DESCRIPTION
**Pull request by xallos**
Greek characters problem in Client Notice Manager fix : If the special characters protection follows the html entities protection then some greek characters like A are first translated into &alpha; and then into &amp;alpha; which breaks the content.

### CODE REVIEW

**Comment by motters** [comment]
So what you are saying is ethier use specialchars or html entities?

I knew there was a clash with the two and i applied a fixEntitys function but obv i only tested for english oops :(

I'll have a look at this problem. Probs just use htmlspecialchars as i think that should cover the xss protection and just drop out html entities

**Comment by xallos** [comment]
Yeap, I wasn't aware too, but it seems that it is clearly stated in the documentation. In the comments on the side of the code (not php comments) I found another (perhaps better?) alternative. Check-it out. If I can be of any help I'd be more than happy.

**Comment by allebb** [comment]
Merging for the 10.1.0 release but needs testing to ensure doesn't break current client manager code. - Cannot test at present but want to get it merged to sort out some of these pull requests to ensure they are included in this next release.

**Comment by Caffe1neAdd1ct** [comment]
I'll put this on the testing list!

**Comment by allebb** [comment]
Cheers Kev! - I'm being choosey about the merge requests I accept, so
please dont pull anymore until I've reviewed them!

Cheers,
Bobby

**Comment by Caffe1neAdd1ct** [comment]
No worries I wanted to get the 10.1.0 merge done so i could start testing
this evening, I'll leave them be for now, however I will be committing to
master this evening with fixes / changes so merges may become outdated...

**Pull request closed without merging**
