### PR TITLE
Fixed HTML entity syntax

### PR DESCRIPTION
**Pull request by jacobgelling**
`&reg` was to changed to `&reg;` to comply with the W3C specification of character entities.

Note: Theme files seem to already use the correct syntax.

### CODE REVIEW

**Comment by allebb** [comment]
Hopefully this won't have any weird affects on the SQL script (when running the import eg. ';' character needing escaping) but I'm assuming you've tested so will merge and fix if after further testing turns out this is broken.

**Comment by jacobgelling** [comment]
Sorry, I haven't tested it and will need escaping as you say. I should of thought of that before!

**Comment by allebb** [comment]
Ok - If you could do me a favour... Can you escape the characters, test and
resubmit a new pull request... would save me time as I'm really trying to
get other more 'important' things sorted for the release.

Cheers,
Bobby

**Comment by lottfy** [comment]
this changes will not apply to whom will update only who install need sql.patch

**Comment by jacobgelling** [comment]
Okay, I'll test it and also put a entry in the sql.patch file then submit a new pull request.

**Pull request merged**
