### PR TITLE
Updating login to match core theme and cleanin it up a bit

### PR DESCRIPTION
**Pull request by stokes84**
Just updating the login to match the core theme and also murdered the prettyCheckables plugin.

### CODE REVIEW

**Comment by stokes84** [comment]
Has anyone tried to run the password reset yet? I wasn't getting it to take my new password although the callback and alert were firing fine.

**Comment by Caffe1neAdd1ct** [comment]
Working fine for me, make sure when you updated cnf/security.php didn't get
wiped...

**Comment by stokes84** [comment]
Thx, it's gotta be my setup then, I'll get her fixed. Just making sure I wasn't chasing rabbits.

**Comment by jasondavis** [comment]
At first I really didn't like it but I guess it's starting to grow on me after looking at it for a while.

To help in Bobby deciding if he wants to keep it though, here is a screenshot of what these changes look like...

**Comment by stokes84** [comment]
Whatever's clever :) Could  prolly use some box shadow inside to transition to the white and maybe gradients at the top and bottom, pretty minimalist as it stands now. She's a start tho lol

**Comment by jasondavis** [comment]
I would stay away from the shadows as Bootstrap 3 doesn't use any

**Comment by jd1pinoy** [comment]
How about bootstrap.css
/\* Line 1272 */
input, select, textarea
{
  width: 100; ==>> width: 75%;
}

to fix alignment of "Create a new MySQL® database" - "text input" area that over lap.

**Comment by TheNigelist** [comment]
I like the one that I originally pushed (with the Bootstrap 3 changes) I don't like the dark theme really but it's not my decision.

**Comment by stokes84** [comment]
Was just trying to bite the style of the CP to match so it all meshes while fixing the alerts, killing off checkbox plugin, and cutting some fat. Login could still use a bootstrap only overhaul for simpler theming, there's always room for improvement :)

**Comment by TheNigelist** [comment]
Yeah bro I know. Just voicing my opinion.

**Comment by allebb** [comment]
Has anyone got time to create a different coloured version of the new
theme, maybe a blue theme (same style but just different colour scheme), I
personally like the dark theme but maybe (if someone has some free time
they can create a 'blue' or  'green' version alternative)...??

**Comment by TheNigelist** [comment]
I don't think that it will take much to create an alternative colored theme. I would volunteer but I've recently started working full time (concrete cutting) and I'm a bit stuffed at the end of the day. I could look at it tomorrow though.

**Comment by jd1pinoy** [comment]
I may volunteer too, on my extra time ;)

**Pull request closed without merging**
