### PR TITLE
New Login Theme

### PR DESCRIPTION
**Pull request by stokes84**
Gutted the login using the latest bootstrap css pulled from the bootstrap repo to utilize a few classes I wasn't seeing that I was using while tinkering on bootply. Fixed the CP issue regarding padding on the sidebar the update caused. Made the login.css easy to apply simple themes and stuck a couple little examples in there. Removed the pretty checkables resources now that it's not being used. Added a couple ZPanel logo images (white and black) for light and dark themes. Also added a function to reset the URL when you close an alert, was buggin me while I was refreshing and testing dunno if this needs to stay not sure how older browsers will react to it.

selection_004
selection_005
selection_006

### CODE REVIEW

**Comment by jasondavis** [comment]
Looks good but 3 issues....

#### 1)

There is a very excellent reason I have not included the latest build of Bootstrap 3...as there have been hundreds of new commits to Bootstrap in the past 2 months, the current Bootstrap 3 library that I have included with the project **MUST** be used otherwise a ton of template files and PHP need to be edited again.

I had briefly discussed this with Bobby this week about updating all the code but the is a **code freeze** which I don't think you knew about!

By you including your own version of Bootstrap for just the login page is not really practical to load 2 versions of such a large library when we can get by with just 1... 

_UPDATE_
Even worse, you have simply over-written the old version

If you insist that you have to change the current login page, please utilize the Bootstrap file included with the project already as the current and future final BS3 will require some extra classes and edits to be applied to the template files and there is a freeze on that right now.

#### 2)

Editing the core Bootstrap file is never a good idea!  If you need to over-ride Bootstrap, you really should do it in the `style.css` file so that `bootstrap.css` remains un-edited

#### 3)

You have actually over-written recent work, you should always run `git pull origin master` to get the latest copy of code before you make edits, you have overwritten some recent work such as `#module-search-wrap`

#### Lastly

I don't want you to take this being hard on you but you can see these are some serious issues that affect all the 100+ hours I have just put into this theme, so i'm not going to let it get ruined without saying something.

Also I realize you don't really know what's going on so its a good idea to communicate with others

**Comment by stokes84** [comment]
Sounds good, can always toss in new bootstrap classes utilized within the login css, it's only a few. Didn't realize that original bootstrap stylesheet was two months old, a quick eyeball test of a few modules looked like it was working fine but I'm sure you could find something. Shouldn't take too long to update when you go that route.

Like I said, didn't see anything break or even bend upon updating and the one thing I did notice I fixed. Seems it'd be pretty easy to push it then tweak as needed given the state I saw it in.

Yep, saw those two small commits earlier I forgot to pull, already had em queued up but had to bounce out right after I originally submitted this request so that wasn't an issue. 

Yep you're right, I'll stick to one liners and let you guys do the heavy lifting.

**Comment by jasondavis** [comment]
Yeah the problem is I just tested the latest build 2 days ago, discussed updating the fixes with Bobby but decided against it do to the code freeze.  There is a,lot more then a couple things to change when you get into every module.  It's not doable, I had said I could have it 100% in less then a day.

A few other things have changed as well, icons are no longer a part of Bootstrap, they were just removed and also TypeAhead has been removed.  I just updated TypeAhead, it looks like you don't have that new version yet but it;s been updated this past week

I agree it should be done but I also think at this stage it is better to wait for the final release of Bootstrap3 before doing it instead of doing it 2 or more times.  BS3 is being committed to daily for several months and still is with no estimated release date even.  Last I heard it could still be several months away

**Comment by stokes84** [comment]
Agreed, avoid the unnecessary work and wait for it to stabilize a bit more.

**Pull request closed without merging**
