### PR TITLE
Merge master branch with 10.1.1 for next release.

### PR DESCRIPTION
**Pull request by TheNigelist**
According to to my screen, branch 10.1.1 is 57 commits behind master which would potentially mean that none of the new bug fixes will be in the release.

### CODE REVIEW

**Comment by allebb** [comment]
I honestly don't know what the heck is going on then PS2Guy as I've been merging everything to the master branch lol! - Looks fine from where I'm sitting and also no one else reported that these features and bugs don't appear to be fixed. - Closing this PR as I think you may be getting confused with the fact that YOUR fork is 57 commits behind the 'origin' master branch.

**Comment by TheNigelist** [comment]
Can you please check the 10.1.1 tag because that's where I was looking. Also when you click on release it's telling me that there have been 2 commits to master since you tagged 10.1.1.

**Comment by allebb** [comment]
Yes that is correct, i have merged 2 PR's since the release, these are for the next release though and hence why not re-tagging today's release.

**Comment by TheNigelist** [comment]
Now I'm seeing 4 commits to the master branch as in the picture below.
github1

And here I'm seeing 59 commits to master since you tagged 10.1.1. 
github2

To me it looks like branch 10.1.1 (which the installers/upgraders use) is behind the master branch by 59 commits. Meaning all of the latest bugs haven't been fixed in 10.1.1 because it was  tagged a while back and never re-tagged.

I could be totally wrong and this will be my last comment on the subject if it is.

**Comment by allebb** [comment]
I honestly don't know what you're doing but i'm 95% sure that everything in the master is correct and that it is NOT out of date, i've been committing and merging on that repoi

Just in case i'm the one going crazy here... Maybe @motters @5050 and @AndyKimpe can see if they also think that the master is out of date?

**Comment by TheNigelist** [comment]
Yes I agree. 
The Master is up-to-date but the 10.1.1 branch isn't. (Where the installers install from)
From where I'm sitting it looks like it needs to be merged with the master branch so that it's up-to-date also as it's 59 commits behind the master branch.

**Comment by allebb** [comment]
It can't be lol, i re-tagged it from the 'master' on Friday lol! Ok queston - can you confirm that if you install a fresh version of 10.1.1, does it or does it not contain any of the fixes it is showing needs to be merged?

I honestly can't see how you can be right as other people should have reported issues by now lol...

I can only assume that you didn't rebase your fork after i moved the repo from bobsta63/zpanelx to zpanel/zpanelx about a month ago?

**Comment by TheNigelist** [comment]
I get no robots.txt which was one of the last commits and I don't get the dns fixes from @5050.

I'm viewing all of this from https://github.com/zpanel/zpanelx. My fork is now current.

https://github.com/zpanel/zpanelx/tree/10.1.1 shows that this tree was last authored a month ago.

**Comment by allebb** [comment]
Right ok... after seriously wondering if I was the one going crazy I did some digging and I can see why you are getting confused... firstly, it is YOUR clone (fork) that is showing the last tagged 10.1.1 as being over a month old, however the official repo zpanel/zpanelx shows it as 5 days old (which is correct).... see my screenshots:

This is your fork (clone)
screenshot 2014-03-04 08 24 37

This is the official release:-
screenshot 2014-03-04 08 22 47

As you can see from the below screenshot, 5050's DNS fixes ARE included in the current 'master' tag (and therefore should be installed with the new installers):

screenshot 2014-03-04 08 22 27

What you need to do it bring your fork (clone) of ZPanelX up to date with the 'origin master', check out this post: http://stackoverflow.com/questions/7244321/how-to-update-github-forked-repository

Cheers,
Bobby

**Comment by TheNigelist** [comment]
Okay.

I made a clone of the latest release earlier.

I don't want to argue anymore.

**Comment by allebb** [comment]
Seriously dude, I don't know what to say... Everything with the master looks good to me, maybe others like @5050 @AndyKimpe etc could have a look for us too as it concerns me that you are so adamant yet everything except your clone looks good to me?? 

Have you tried installing with latest installers? Does that install the DNS fixes as per my last screenshot?

I'm not being funny i just cant see any issues lol??

**Comment by TheNigelist** [comment]
It's not the master I'm talking about.

It's the 10.1.1 tag. The installers don't install from the master repo.

I just downloaded both master and 10.1.1 and did a compare of the 2 DNS manager files and they appear to be the same.

However when I view https://github.com/zpanel/zpanelx/tree/10.1.1 in a browser I see the picture below that tells a different story which is why I created this P/R. It turns out according to my downloads that I appear to be wrong so I'm sorry for the confusion.

github3

**Comment by jacobgelling** [comment]
I'm agreeing with PS2Guy - on the main repository the 10.1.1 tag is about a month old to the master. Does this mean the new installers have missed out a ton of commits? :confused:

**Comment by allebb** [comment]
Right, this is really starting to annoy me now :(

Wrong actually the tagged hash is correct, the branch however is not :(... WTF, how the hell has this happened? Click on these two, links and look at the dates:-

screen2

Surely then, all the testing that people have been doing couldn't have been actually testing that latest changes lol!!???

The fact that PS2Guy said he has compared the files and they are the same I think this must be something weird that GitHub is displaying... Each time I have deleted the tag and re-tagged so it must be technically correct as I've done the same process for each of the beta tags and we know that previous bugs that was an issue have been fixed with newer tagged releases.

Maybe I should just delete the branch lol... It is the tag that we should be pulling from lol!

**Comment by jacobgelling** [comment]
Ahhhh, that's what the problem is - I'm getting muddled up with the branch and tag...

It's probably best to delete the branches and just use tags.

**Comment by allebb** [comment]
Branch has now been deleted, that I think is what was causing all of the confusion :+1: 

@PS2Guy If you re-fork now or update your fork it it should straighten things out :)

**Comment by motters** [comment]
Yep everything is fine for me :)

**Comment by TheNigelist** [comment]
Sorry, 

I see where I was getting confused now.
I thought the tag and the branch were the same.
It's been a long last couple of months.

I'll be more careful next time.

**Comment by 5050** [comment]
@PS2Guy : you are a lucky man. I was already confused with github before, I'm now completely sunk!

**Pull request closed without merging**
