### PR TITLE
MD5 Security, More Crons, and Small Typo's

### PR DESCRIPTION
**Pull request by flectron**
This will allow FTP account passwords to be encrypted. Added 1 Month and 1 Years crons in the code. Fixed a few typo's :+1:

### CODE REVIEW

**Comment by Caffe1neAdd1ct** [comment]
Ok before this merge goes ahead:

One of those links is showing doing a patch to ProFTPd which i am very reluctant to do to everyones servers due to the last incident of Postfix being patched to do mail delivery.. which was annoying to reverse.

The other link shows we need to store {md5} in front of the md5 hash in the database.

So two questions flectron before we can do this merge:
1) Does this work without patching ProFTPd
2) Has the code been changed to store the MD5 correctly and does it work?

**Comment by flectron** [comment]
1) Does this work without patching ProFTPd? Yes, does not effect the configs only the password in the core database
2) Has the code been changed to store the MD5 correctly and does it work? Yes, instead of using a plain password in the core database it uses MD5 to insert a encrypted version of the password. Basically more of a zPanel security enhancement than a configuration patch

**Comment by allebb** [comment]
I think I'll close this pull request as I don't think that the correct
implementation is to just hash the password stored in the zpanel_core
database, I was under the impression that ProFTPd was reading from this
table (its been a while since I last visited this part of my code) but I
guess if you've not had to make any config changes to ProFTPd then ProFTPd
must be reading a plain-text duplicate of the password from the
zpanel_proftpd table and if so, there really is no point of even having
the plain-text version MD5'd as we wouldn't be able to display it on the
front-end anyway...

I might as well just remove this 'feature' and column from the core
database if its not used by ProFTPd there really is little point of keeping
this in... its bad that we are still storing a plain-text password in a
non-core table anyways let alone having it duplicated just so user's can
remember it once they've logged in.

**Comment by Caffe1neAdd1ct** [comment]
I agree that the password shouldn't be in plain text and definitely not just displayed inside the module... getting rid of the duplicate column and storing as a hash would be a good step to securing this module...

**Comment by allebb** [comment]
Agreed... I'll remove it, its the safest way! :) - At work at the moment,
I'll implement the removal of the column this evening.

**Comment by jasondavis** [comment]
Removing this DB column, is removing the password displayed on the page here?

**Comment by Caffe1neAdd1ct** [comment]
Yep that's part if the task, removing the displayed password plus duplicate
DB column.

On 26 Mar 2013, at 16:49, Jason Davis notifications@github.com wrote:

Removing this DB column, is removing the password displayed on the page
here?

[image: 2013-03-26_12-47-29]https://f.cloud.github.com/assets/186818/304088/e24aefb6-9634-11e2-9322-12754fb6f2eb.png

—
Reply to this email directly or view it on
GitHubhttps://github.com/bobsta63/zpanelx/pull/28#issuecomment-15470528
.

**Comment by allebb** [comment]
Yes, correct... If people cant remember their passwords, then in future the user will simply just have to use the reset function! - end of discussion :D

**Comment by Caffe1neAdd1ct** [comment]
Agreed :+1:

**Comment by Caffe1neAdd1ct** [comment]
So looking at this merge there are two files to be merged and Bobby will look at the FTP controller change.
pssst how do you merge only part of a merge request?

**Comment by flectron** [comment]
Sweet. Thats a better idea :P

**Comment by jasondavis** [comment]
@Caffe1neAdd1ct I have been studying Git usage for the past 4 days lol so that's the only reason i'm responding as it's fresh to me.  You can't break up a Pull Request so would have to use `git cherry-pick` or `git rebase -i` to get rid of the bad commits

However of the 3 commits here 2 of them can be ignored which leaves 1 commit with just a few lines of code, might be easier to just edit it in and make a new Pull request

**Comment by allebb** [comment]
'''However of the 3 commits here 2 of them can be ignored which leaves 1 commit with just a few lines of code, might be easier to just edit it in and make a new Pull request'''

^^ - Absolutely, the other issue is that those commands you've used are for the Git Client, we can't use them on the GitHub merge interface. - I'll simply get the diff version of this merge request and then discard the FTP change :)

**Comment by allebb** [comment]
Cleaning up old merge requests that cannot be merged automatically.

**Pull request closed without merging**
