### PR TITLE
Version control the API url

### PR DESCRIPTION
**Pull request by trojanspike**
I don't think there are many people using the API & if there are it would just be an easy change in their connecting URL.

I'm doing some changes to the main API , taking it away from XML and getting it up to standard using cURL & json. Making it more secure .

I'll also be updating the PHP xmws client.
 https://github.com/trojanspike/xmws-php-client/tree/release/1.1
If anyone wants to contribute , feel free.

### CODE REVIEW

**Comment by ghost** [comment]
Great

**Comment by TheNigelist** [comment]
I use the API a lot for my billing module. Will be keeping a close eye on this.

**Comment by allebb** [comment]
I see little point in versioning this atm especially as there are no other
versions of the API avaialble and really I have no intension in changing
this until the next release so really, don't worry Nigel... this isn't
getting merged :)

**Comment by trojanspike** [comment]
I'm making a V2 which is why I need the version control otherwise I'll be hacking the current version.

**Pull request closed without merging**
