### PR TITLE
Cleaned up login.ztml plus some other fixes

### PR DESCRIPTION
**Pull request by jacobgelling**
Just used the NetBeans auto formatting tool and fixed some small typos in login.ztml - for example `class="panel-content form-horizontaL"` was changed to `class="panel-content form-horizontal"`

Nothing major has been changed really - just lots of little things.

Tested and all seems to be working fine :thumbsup:

### CODE REVIEW

**Comment by jacobgelling** [comment]
Also just added min-height to panel headings which stops modules without descriptions in their header (ex DNS Manager - should it have one?) having their icons overlap into the panel's content.

Perhaps this addition should be added to light.css aswell?

**Comment by jacobgelling** [comment]
Corrected the tmp directory path for phpMyAdmin. This fixes http://bugs.zpanelcp.com/view.php?id=661

Tested and works on Linux - should work on Windows.

**Comment by lottfy** [comment]
@jacobg830 Will testing your patch about tmp directory good to re-update phpmy admin to latest  version "4.1.7"

**Comment by jacobgelling** [comment]
@lottfy I'll be updating phpmyadmin (since a new one has just been put out) and also update roundcube soon(ish).

**Comment by allebb** [comment]
:+1:  Perfect!

**Comment by allebb** [comment]
I've had to merge these commits locally as they are not available for auto-merging on here. I won't commit the temp path change as you've mentioned you'll upgrade and push a pull request for new version(s) of phpMyAdmin and RoundCube so if you could just make sure that the temp path fix is included in your next PR that would be great :)

**Comment by lottfy** [comment]
@jacobg830 
    phpSysInfo 3.1.9 released (February 8, 2014) rember to edit index with session check

**Comment by jacobgelling** [comment]
@bobsta63 Strange that auto merge didn't work - I was probably behind the master or something.

@lottfy I think I'll just update all the apps then. The session check is also added to xml.php (though guides on the forum seem to miss this out).

**Comment by lottfy** [comment]
@jacobg830 go to this link :https://github.com/jacobg830/zpanelx/settings
go down and choose "Delete this repository" then go to https://github.com/zpanel/zpanelx and fork it and begin work mate

**Pull request closed without merging**
