### PR TITLE
Allowed Plus sign (+) in email

### PR DESCRIPTION
**Pull request by zainengineer**
Plus is valid in emails & exclusively used in gmail alias. Very useful
if you want to create different users with your own email address

In addition added .idea (phpstorm working environment files) in
.gitignore

### CODE REVIEW

**Comment by jacobgelling** [comment]
Hmm, I never knew that. Emails can in fact contain: ! # $ % & ' \* + - / = ? ^ _ ` { | } ~ .

**Comment by zainengineer** [comment]
yes specially + is very common 
for example if you have email address jacob.zpanel@gmail.com 

Gmail can create automatic alias of your email if somebody sends you email jacob.zpanel+test.add.account@gmail.com which is automatically sent to your original email account. This allows you to work around unique email restriction in when testing different applications.

**Comment by crazyscience** [comment]
+1 I just came here to report this bug. Looks like you guys beat me to it!

**Comment by zainengineer** [comment]
but it is not merged yet. I think :(

**Pull request merged**
