### PR TITLE
Stokes84 missed some < symbols when he added the favicon support. It was...

### PR DESCRIPTION
**Pull request by TheNigelist**
... causing the favicons to not display.

### CODE REVIEW

**Comment by allebb** [comment]
Added in commit: https://github.com/bobsta63/zpanelx/commit/c816106af38ff4d45468b9e34de43192cdbf39a8

**Comment by TheNigelist** [comment]
Damn beat me to it. Good that you found it.

**Comment by stokes84** [comment]
Thx :)

**Comment by allebb** [comment]
No problem guys :)

**Pull request closed without merging**
