### PR TITLE
Added web service capabilities for sub_domains module

### PR DESCRIPTION
**Pull request by alexeyismirnov**

### CODE REVIEW

**Comment by allebb** [comment]
Thanks for your contribution @alexeyismirnov :+1:

**Comment by jasondavis** [comment]
@bobsta63 @alexeyismirnov Is this for like an API use?

**Comment by allebb** [comment]
Well, ZPanel already provides a modular approach to web services, this change simply adds missing sub-domain web API methods.. I guess this was missed out when we split the Domains module from managing both domains ad sub-domains out to their separate modules.

If you see the documentation link on the Zpanel website you should see a document named 'XMWS' - this is the name of the modular XML based web service... Just not utilised by many people.

**Comment by allebb** [comment]
...I'm figuring though if you didn't know about it that maybe other people didn't realise that there has been an API since ZPX was first released lol :dancer:

**Comment by jasondavis** [comment]
Got it thanks, I knew of the API just wasn't sure if that was what this was for.  I would say that possibly others overlook it though .  I'm still very much interested to hear anything about the new project if you are using Laravel still...I have been building a lot of big projects lately with Laravel, it's truly my favorite thing in PHP in years, love it!

**Comment by allebb** [comment]
Hi Jason,

Sorry for the late reply, Well with regards to the new project, ZPanel (as
a project and brand) is now owned by someone else and he has expressed a
wish to keep with the same version for now and to concentrate efforts on
ZPX, so a new release will be released hopefully this week!

With regards to the next major version of ZPanel, yeah we've started it in
Laravel but then turned attention back to ZPX as mentioned above... I've
written 10+ applications in Laravel now also, I know what you mean, Laravel
really is just the most awesome framework I've ever used, I don't want to
ever have to use something else now :)

**Pull request merged**
