### PR TITLE
Updated PhpSysInfo and phpMyAdmin to their latest stable versions

### PR DESCRIPTION
**Pull request by jacobgelling**

### CODE REVIEW

**Comment by Caffe1neAdd1ct** [comment]
Just a quick comment, be careful updating phpmyadmin as I remember it had to have a few settings changed due to security implications.

Double check the commit history on the phpmyadmin folder before merging...

Also make sure the setup folder is deleted, I can't check this right now as I'm replying from a mobile.

**Comment by allebb** [comment]
Yeah looking at the code the phpSysInfo/index.php file is also missing our session checking stuff, not to worry... I'll merge this tomorrow and re-add the session checking stuff and custom changes that we normally have added to the phpMyAdmin configuration. - Thanks for providing the latest changes though jacobg830!

Cheers,
Bobby

**Comment by jacobgelling** [comment]
I already deleted the phpMyAdmin setup folder and I added the same changes as before to PhpSysInfo (session checking) but not to phpMyAdmin and I thought it didn't use it.

**Comment by allebb** [comment]
Thanks Jacob, I'll merge this request, Mainly was referring to the
'SuhosinDisableWarning = true' and check that the UploadDir and SaveDir
options are set to use the '../tmp/' path but thats all :) - I'll merge and
add any minor fixes as and if required :)

**Comment by allebb** [comment]
Just checked and see you already took care of the those settings :+1: Thanks buddy :) - I didn't need to do anything - result!

Cheers,
Bobby

**Pull request merged**
