### PR TITLE
Changing the theme and adding a new login.ztml

### PR DESCRIPTION
**Pull request by TheNigelist**
Added d3c0y's login.ztml and the files needed to make it work.

Added <# ui_tpl_assetfolderpath #> to the master.ztml in all places needed as it's a better standard to use instead of having it hard coded in.

Added <# ui_tpl_year #> to Copyright as it was also hardcoded with the date.

### CODE REVIEW

**Comment by TheNigelist** [comment]
Also forgot to mention that I deleted the old theme and renamed the new theme as the old theme (if that makes sense?)

**Comment by allebb** [comment]
OK buddy! - I guess that will save us updating the install SQL to change
the default theme name lol!

**Comment by Caffe1neAdd1ct** [comment]
Didn't think of that!!

Cool one less SQL update... won't argue with that...

**Comment by TheNigelist** [comment]
I just figured it would be easier as this will now be the default theme. I'm not even sure if any of the old themes still work??

**Comment by Caffe1neAdd1ct** [comment]
Ah that could be quite a big issue...

We may need to do a SQL update anyway to set all clients and resellers and
the zadmin to use the new default theme...

**Comment by Caffe1neAdd1ct** [comment]
Anyone running custom themes could have their whole panel unaccessable
after the update if we don't run a SQL to set the default..

**Comment by TheNigelist** [comment]
I was going to do some testing to see.

**Comment by Caffe1neAdd1ct** [comment]
If you can that would be great!

**Comment by TheNigelist** [comment]
Just uploading the latest changes to my server now.

**Comment by allebb** [comment]
Yeah thats nothing major, thats just...

UPDATE x_accounts SET WHATEVER_THEME_IS_AGAIN = 'zpanelx'; .... then Boom!
- Done :)

**Comment by Caffe1neAdd1ct** [comment]
I'll get that added to the upgrade SQLs

**Comment by allebb** [comment]
Im now doing that mate :)

**Comment by Caffe1neAdd1ct** [comment]
lol fair enough i'll scrub that off this evenings to-do list then :p

**Comment by allebb** [comment]
:)

**Pull request merged**
