### PR TITLE
Changing the icon's from Bootstrap to ZPanel.

### PR DESCRIPTION
**Pull request by TheNigelist**
Please ignore the change to master.ztml as I use a slightly modified version that I keep forgetting to change before I push updates.

### CODE REVIEW

**Comment by allebb** [comment]
God man, are you like addicted to opening pull requests lol!!! - I just spotted this myself 5 minutes ago, was going to get this sorted when I got back from lunch but I'll merge this now then :+1:

**Comment by TheNigelist** [comment]
Nah not addicted. Just want to help get everything sorted for you guys. Every little bit helps aye.

**Comment by jasondavis** [comment]
Just a quick note... The theme is using Bootstrap 3 beta while that login page is using Bootstrap Responsive v2.3.1 so we are including a huge Bootstrap css just for the login file.  I know this can be improved later on but I just thought I would bring it to attention at least

**Comment by allebb** [comment]
Ok cheers Jason! - I'll look at converting over the login screen over to use Bootstrap v3 :) - Fantastic job you've done on the theme, we've had to make a few changes here and there but its fantastic buddy... great work! :D

**Comment by jasondavis** [comment]
thanks, it really did turn out better then I originally envisioned...I have been following a long to see what all has changed, you guys have been busy!

**Comment by Caffe1neAdd1ct** [comment]
I may have been up to about 3am last night... not planning quite as much this evening :)

**Comment by allebb** [comment]
@Caffe1neAdd1ct  - I saw that this morning on one of your later commits... I was like... screw that lol... I need my beauty sleep,especially after doing dirty work last night like tiling lol ;)

@jasondavis It is really good mate, it really does make ZPanel look more 'business'/corporate like now... :+1:

**Comment by jasondavis** [comment]
Sometime I'll try to write up/document some of the feature that people will be able to use in there own themes and modules  

for example a button like this  `<button class="button-loader btn btn-primary" type="submit">Text</button>`
has the `button-loader` class,  this triggers my javascript loading screen to show when the button is clicked so it should only be used on button clicks which end up reloading the page,, and not button clicks that launch a popup window, otherwise the spinner/loading screen will stay open.

I will also show how to use the Dialog I made it pretty flexible so you can pass in callback functions and set everything through a simple api

**Comment by allebb** [comment]
Wow... yes that would be most usefuil Jason! - I'm glad you just told me
that as that is going to be dead handy for when I update my BindHub.com
module to play more harmoniously with the new theme :)

I'll be making use of the button-loader class then as the module makes a
web service request and would be dead handy to use that to 'keep the user
calm' lol

**Pull request merged**
