### PR TITLE
New DNS Manager

### PR DESCRIPTION
**Pull request by jasondavis**
This is very important to make all the new css tabs and the extensive amount of re-factoring as well as all the JavaScript to work

### CODE REVIEW

**Comment by allebb** [comment]
Huh?? - Seems to be a deletion pull request... there is no content lol!

**Comment by Caffe1neAdd1ct** [comment]
All i can see when loading the DNS module up with the new code is <<<<<<< HEAD

Need to get the new code in before I can confirm the release.

**Comment by allebb** [comment]
Yeah, I just closed Jason's pull request as it appeared to be screwed lol!
- I didn't merge it! - Like you say it just had a <<< head line etc. -
  Seems like a screwed merge via. a desktop diff tool.

I guess Jaon will submit another merge request shortly :)

**Comment by jasondavis** [comment]
It was all there, it just looks that way.  1 of the commits removed it all but the other added it back, if you hit the View File button you will see.  I will send a new request though with a new version.

The <<<<<<< HEAD that is in the current file is because Git adds that when there is a merge that needs attention so that's what happened as that was the 1 file that wouldn't merge.

Github is not showing this commit properly for some reason however the file is all there even though it says it deleted all the contents, you can confirm by viewing the actual file above however I sent a new updated pull request

**Comment by allebb** [comment]
That was very strange, at the time I checked both of the commits in the
pull request... I see there is a third now so I guess that sorted it :) -
Kev's merged it now anyways so its all good :)

Cheers Jason :)

**Comment by Caffe1neAdd1ct** [comment]
Sorry bobby had to merge in the changes as i'm working on the project now...

Just committing a new system class for which is now going to be the ONLY
class anyone will be allowed to run system() commands through... (bit like
when i put in the bindQuery, all sql queries are supposed to go through it
regardless.. )

**Comment by allebb** [comment]
Thats fine mate, I'm a little stuck on something else at the moment - Nikki
(my GF) is kicking my arse about getting the tiles in the bathroom done so
I'll be working on that tonight and tomorrow (its abit like putting a
muzzle on a dog i'm affriad lol!).

I'll review the code once you've sorted it mate!

**Comment by Caffe1neAdd1ct** [comment]
No worries i'll carry on, maybe you can review all the changes at the
weekend or rely on me to check them... (if you dare :p )

**Comment by allebb** [comment]
Well mate, I'd expect you to fully check them anways lol... I'll be able to
check them (a quick look over the code tomorrow at work) and then test the
changes in a Zpanel environment later this week :)

Yeah, I'd better go and get on otherwise I'll be sent to the gas chamber!

**Pull request closed without merging**
