### PR TITLE
Add missing icons in navbar for installed modules

### PR DESCRIPTION
**Pull request by stokes84**
Currently if you install a module there's not the associated class within the css to provide a nav icon for it (core modules get the clean sexy icons only). The main module layout handles this fine and pulls from the module assets. We're just going to make the navbar title grab an icon from the assets for aftermarket modules as well.

<hr>

<p align="center">
<b>Before This Patch</b>
<br>

</p>

<hr>

<p align="center">
<b>After This Patch</b>
<br>

</p>

Side Note: IE10-11 dropped filters support among other odd changes. This can be fixed via javascript but at the cost of a bit of overhead. A workaround is detailed [here](http://www.majas-lapu-izstrade.lv/cross-browser-grayscale-image-example-using-css3-js/) and the unique target-able classname will help with this.

### CODE REVIEW

**Comment by ghost** [comment]
yep why not.

Good

**Comment by stokes84** [comment]
Sidebar icons can get some love for custom module icons too @ ab384b90f76aed96b92386db8eb0121fcc46fdf1 and @ bb6083841365726a3bfbcd986a52783fc89e7d00

<p align="center">

</p>

**Comment by stokes84** [comment]
One more for the road...

Commit 8423752cd14e1a832ca3d28ff00dd0516933578a turns this...

<p align="center">

</p>

Into this...

<p align="center">

</p>

**Comment by allebb** [comment]
Awesome stuff @stokes84  - I'll merge and test later (at work atm :()

**Comment by lottfy** [comment]
@stokes84:After apply your changes go to zpanelconfig >>>Icons per Row change it to 3 so will be 3 module icons per row but not updated

**Comment by stokes84** [comment]
thx for the heads up, I'll take a peek at that

**Comment by stokes84** [comment]
@lottfy before I dig too deep are you able to confirm this was working before this update? My initial trace sees this being called in what looks like a deprecated portion of the Dryden template system.

**Comment by TheNigelist** [comment]
I can't get your greyscale commit working @stokes84. Is there something that I'm missing??

Is it spelt correctly??

greyscale

Running the latest code.

**Comment by allebb** [comment]
Are you using IE Nigel? - Chris said the other day that IE dropped CSS
support for greyscale so would have to implement a JS solution for IE
users, not sure if this has been done as yet but that may be what is
causing your issue... try it in Chrome/Firefox if you are using IE?

**Comment by TheNigelist** [comment]
Nah firefox boss. I run Ubuntu Desktop, so no IE there.

I've tried clearing the cache of both ZPanel and Firefox and I still am at a loss as to how this works.

**Comment by allebb** [comment]
Ok bud, I'll have to give it a try myself unless Chris Stokes comes back to
us soon with a fix/reason/confirmation that it does work ;)

**Comment by jd1pinoy** [comment]
Grey scale is not supported in IE

filter: url(filters.svg#grayscale); /\* Firefox 3.5+ _/
filter: gray; /_ IE6-9 _/
-webkit-filter: grayscale(1); /_ Google Chrome & Safari 6+ */

**Comment by allebb** [comment]
Yep that is what I said earlier on, I was just saying that Chris had said
that the work around for IE was to use Javascript and apply some kind of
filter over the image as opposed to using CSS tricks as the current CSS
implementation is not supported on IE :)

**Comment by stokes84** [comment]
Hey ya sorry about that, I'm noticing css filter support is [pretty spotty](http://caniuse.com/css-filters) and that svg has much [better support](http://caniuse.com/svg-html5). Just a few quirks here that cause the time vampire to strike lol. Should be done tweaking a solution here shortly for icon overlays so they can be colored for themes and supported in Microsoft's abomination as well as Gecko and Webkit.

**Comment by allebb** [comment]
Awesome Chris, looking forward to recieving the pull request :)

**Comment by stokes84** [comment]
So I almost got it knocked out tonight. After all was said and done the only viable option to allow theming while supporting IE was utilizing html5's [canvas](http://caniuse.com/canvas) animation. Holy overhead tho batman, it's a bit of code for such a simple task. I'd post a JSFiddle but canvas has a strict cross-domain policy so it'll break anywhere but @ it's origin. I'm going to tweak it a bit tomorrow night (Seattle time) and bust some JSPerf tests on it.

Here's what I got so far tho...

```
function changeColor(imgObject, imgColor) {
    // create hidden canvas
    var canvas = document.createElement("canvas");
    canvas.width = 40;
    canvas.height = 40;

    var ctx = canvas.getContext("2d");
    ctx.drawImage(imgObject, 0, 0, 40, 40);

    var map = ctx.getImageData(0, 0, 40, 40);
    var imdata = map.data;

    // convert image to grayscale first
    var r, g, b, avg;
    for (var p = 0, len = imdata.length; p < len; p += 4) {
        r = imdata[p]
        g = imdata[p + 1];
        b = imdata[p + 2];

        avg = Math.floor((r + g + b) / 3);

        imdata[p] = imdata[p + 1] = imdata[p + 2] = avg;
    }

    ctx.putImageData(map, 0, 0);

    // overlay using source-atop to follow transparency
    ctx.globalCompositeOperation = "source-atop"
    ctx.globalAlpha = 0.3;
    ctx.fillStyle = imgColor;
    ctx.fillRect(0, 0, 40, 40);

    // replace image source with canvas data
    return canvas.toDataURL("image/png", 1);
}
```

It'll get called most likely in application.js after we add a class for custom modules in module2column.class.php by iterating over those custom modules (or all modules like I did in the picture) kinda like so....

```
jQuery(window).load(function () {
    $('.custom-module').each($.proxy(function() {
        $(this).attr('src', changeColor(this, '#33CC33'));
    }),this);
});
```

<p align="center">

</p>

Only current issue is the module icons load slow (almost dead last) and they have to exist in the DOM before busting out the canvas magic. We'll have to fade or just flash em all in at once or it'll look god awful seeing modules switcharoo (although just tested in FF and it's seamless, it handles canvas great but chrome and IE still slowish to switch but not bad). Or could just apply the canvas to all icons (as pictured) for uniform color I guess, gotta test more see what looks decent to the eyeballs before I toss more garbage at ya lol.

**Comment by jacobgelling** [comment]
I can't actually test on IE10, but this will probably work fine. Works perfectly on Firefox and Chrome.

Basically, it should use a SVG filter for IE10 making it greyscale without the need for javascript and canvas.

Also, you've added some non-existing CSS prefixes and they are in the wrong order. This is how the greyscale class should look:

```
.greyscale {
    filter: gray;
    filter: url("data:image/svg+xml;utf8,<svg xmlns=\'http://www.w3.org/2000/svg\'><filter id=\'grayscale\'><feColorMatrix type=\'matrix\' values=\'0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0 0 0 1 0\'/></filter></svg>#grayscale");
    -webkit-filter: grayscale(100%);
    filter: grayscale(100%);
}
```

You can see it working at http://jsfiddle.net/3EPDw/1/

I don't think the spelling matters (greyscale or grayscale) but I'm unsure whether everyone prefers to use British or US English.

**Comment by stokes84** [comment]
Made a fiddle [over here](http://jsfiddle.net/d3c0y/6BSsy/) to explain the method to take if this is something you wanna do @bobsta63 Lemme know and I'll submit a pull request.

**Comment by stokes84** [comment]
Hey @jacobg830 I somehow missed that last comment, I'll have to give that a test. I've read that svg overlays are funky in the latest flavors of IE. Everyone seems to have to fallback to polyfills.

**Pull request merged**
