### PR TITLE
Corection DNS

### PR DESCRIPTION
**Pull request by azwyou**

### CODE REVIEW

**Comment by Caffe1neAdd1ct** [comment]
Looks good! Merging into master.

**Comment by allebb** [comment]
That shouldn't have gone to Master.... remember we decided we was going to code the next version on 10.0.3 branch as previously posted in the forums :( - Too late now though I guess, we'll need to delete and re-create the 10.0.3 branch!

**Comment by Caffe1neAdd1ct** [comment]
I'll merge master into 10.0.3 tomorrow evening. 10.0.3 should be regularly merged into master so anyone else branching from master gets the latest stable changes.

**Comment by allebb** [comment]
People NEED to branch from our development branch... we'll just have to
make that clear... it will get tooo messy otherwise mate!

**Pull request merged**
