### PR TITLE
Alerts fix + RoundCube update

### LINKED ISSUE #177: @times; dispaly as x but not close dialog
Updated 
Here  >>> etc\styles\zpanelx\login.ztml LINE 60,67,74,81

Go to your server and logout try to close it not working

### PR DESCRIPTION
**Pull request by jacobgelling**
This pull request fixes #177 by adding some missing bootstrap javascript to the login page.

### CODE REVIEW

**Comment by jacobgelling** [comment]
Just updated RoundCube aswell :wink: The current config files work fine with it. No SQL patches required either.

**Comment by lottfy** [comment]
Not testing round-cube yet so good to know this point incase forget it

WARNING: when upgrading from <= 0.9 the old configuration files named main.inc.php and db.inc.php are now deprecated and should be replaced with one single config.inc.php file. Run the ./bin/update.sh script to get this conversion done or manually merge the files. NOTE: the new config.inc.php should only contain options that differ from the ones listed in defaults.inc.php.

**Comment by jacobgelling** [comment]
Regarding the RoundCube config files - they do still work but it is now just best practice to use one config file. I'm not sure of all the changes that would be needed (such as installers etc) and what ZPanel has changed from the default RoundCube config files.

**Comment by satdav** [comment]
Can I ask you update the roundcube to the latest build

**Comment by jacobgelling** [comment]
@satdav I've already updated to the latest stable version :wink: Just waiting for the update to be approved.

**Comment by lottfy** [comment]
@jacobg830 you must work to apply this PR to installer as .sh

**Comment by jacobgelling** [comment]
@lottfy What to you mean applying this installer as .sh? And what guide?

I don't think any install/upgrade changes are required as the SQL files are the same.

Edit: I see you made some commits on your fork - do they fix the problems?

**Comment by lottfy** [comment]
meaning who will update to e.g 10.1.2 need simple script to apply .sql changes and  also config 
WARNING: when upgrading from <= 0.9 the old configuration files named main.inc.php and db.inc.php are now deprecated and should be replaced with one single config.inc.php file. Run the ./bin/update.sh script to get this conversion done or manually merge the files. NOTE: the new config.inc.php should only contain options that differ from the ones listed in defaults.inc.php.
go to https://github.com/zpanel/installers and open new PR WITH .SH AND CONFIG FILES

**Comment by jacobgelling** [comment]
@lottfy Right but there were no SQL changes and the old config files still work but are deprecated.

**Comment by satdav** [comment]
@bobsta63  can we please get your throughts on this update as I think what it is ready from my side to go live but th @lottfy  is disagreeing with it

**Comment by jacobgelling** [comment]
Ok I get what you mean now. I'll hopefully post a new PR with a merged config file and the sh file soon. Sorry for the confusion haha.

Note to others: this pull request still works perfectly fine but doesn't use the new style of Roundcube config files (yet).

**Pull request merged**
