### PR TITLE
Reopened Pull request 

### PR DESCRIPTION
**Pull request by VJftw**
Double checked, the current master branch for 10.1.0 has not included these fixes.

so, during my testing, I found that using:
include($extra_config);
does APPEAR to be slower than using the original
exec('php .....');

I think, maybe using the change that i've made that uses include instead gives a more real time representation of an install/upgrade/remove using the zppy client. Scripts execute line by line right? So, include will literally copy and paste the lines into the currently executing script (so any lines after in the zppy client will be executed after), whereas exec(''); would create a new process?

The other file change is just a modification to those file management functions that I added to the file handler. They're fully safe,clean and compatible now :)

### CODE REVIEW

**Comment by Caffe1neAdd1ct** [comment]
VJftw

Can you quickly summarise what these changes solve / fix?

Kev

**Comment by VJftw** [comment]
in bin/zippy, install.run, upgrade.run and remove.run will now be able to access ZPanel functions in Windows.

then the dryden/fs/filehandler.class.php changes is just cleaning my own code that I submitted before for Copying and removing a directory contents. 

The main purpose of this commit was to enable people to be able to install AjaXplorer on Windows based servers

**Comment by Caffe1neAdd1ct** [comment]
So this worked fine for linux based servers just failed for windows?

**Comment by VJftw** [comment]
These changes fix things for Windows servers. Linux never had a problem.

**Comment by allebb** [comment]
Hi VJftw, Can you summarise all the changes for me so we can ensure they are added to the change log buddy?

Cheers mate,
Bobby

**Comment by VJftw** [comment]
- The zppy client now executes extra configuration files inline rather than in a seperate process
- Added CopyDirectoryContents, RemoveDirectoryContents, RemoveDirectory functions to the filehandler

**Comment by allebb** [comment]
Lovely, cheers VJ!

**Pull request merged**
